version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: game_assistant_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  frontend:
    build:
      context: ./gameAssistantFrontend/game-assistant-frontend
    container_name: game_assistant_frontend
    restart: unless-stopped

  backend:
    build:
      context: ./gameAssistantBackend
    container_name: game_assistant_backend
    ports:
      - "8080:8080"
    environment:
      APP_PUBLIC_URL: http://localhost:80
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/game_assistant_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_pass
      JWT_SECRET_ACCESS: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
      JWT_SECRET_REFRESH: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: game_assistant_db
    restart: always
    environment:
      POSTGRES_DB: game_assistant_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
