spring:
  application:
    name: gameAssistantBackend

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import:
      optional:application-secret.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/game_assistant_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS:qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==}
    refresh: ${JWT_SECRET_REFRESH:zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==}

ai:
  openai:
    key: ${OPENAI_KEY}
    url: ${OPENAI_URL}
  yandex:
    key: ${YANDEX_KEY}
    url: ${YANDEX_URL}
    catalog-id: ${YANDEX_CATALOG_ID}
  mistral:
    key: ${MISTRAL_KEY}
    url: ${MISTRAL_URL}